// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniLibraryWeb.Data;

#nullable disable

namespace MiniLibraryWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260613105209_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniLibraryWeb.Models.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PublishYear")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Dale Carnegie",
                            Category = "Tâm lý học",
                            PublishYear = 1936,
                            Stock = 10,
                            Title = "Đắc Nhân Tâm"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Paulo Coelho",
                            Category = "Tiểu thuyết",
                            PublishYear = 1988,
                            Stock = 5,
                            Title = "Nhà Giả Kim"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Nguyễn Nhật Ánh",
                            Category = "Truyện dài",
                            PublishYear = 2010,
                            Stock = 8,
                            Title = "Tôi Thấy Hoa Vàng Trên Cỏ Xanh"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Jeffrey Archer",
                            Category = "Tiểu thuyết",
                            PublishYear = 1979,
                            Stock = 3,
                            Title = "Hai Số Phận"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Rosie Nguyễn",
                            Category = "Kỹ năng sống",
                            PublishYear = 2016,
                            Stock = 12,
                            Title = "Tuổi Trẻ Đáng Giá Bao Nhiêu"
                        });
                });

            modelBuilder.Entity("MiniLibraryWeb.Models.Entities.BorrowTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FineAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReaderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("ReaderId");

                    b.ToTable("BorrowTickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            BorrowDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FineAmount = 0m,
                            ReaderId = 1,
                            Status = "Borrowed"
                        },
                        new
                        {
                            Id = 2,
                            BookId = 2,
                            BorrowDate = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FineAmount = 0m,
                            ReaderId = 2,
                            ReturnDate = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Returned"
                        },
                        new
                        {
                            Id = 3,
                            BookId = 3,
                            BorrowDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FineAmount = 100000m,
                            ReaderId = 3,
                            Status = "Overdue"
                        },
                        new
                        {
                            Id = 4,
                            BookId = 4,
                            BorrowDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FineAmount = 30000m,
                            ReaderId = 4,
                            ReturnDate = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Returned"
                        },
                        new
                        {
                            Id = 5,
                            BookId = 5,
                            BorrowDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FineAmount = 0m,
                            ReaderId = 5,
                            Status = "Borrowed"
                        });
                });

            modelBuilder.Entity("MiniLibraryWeb.Models.Entities.Reader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Readers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardNumber = "LIB-ANHTHU01",
                            Email = "anhthu@gmail.com",
                            Name = "Anh Thư",
                            Phone = "0987654321"
                        },
                        new
                        {
                            Id = 2,
                            CardNumber = "LIB-MAING01",
                            Email = "mai.nguyen@gmail.com",
                            Name = "Nguyễn Thị Mai",
                            Phone = "0901234567"
                        },
                        new
                        {
                            Id = 3,
                            CardNumber = "LIB-TUTRAN01",
                            Email = "camtu.tran@gmail.com",
                            Name = "Trần Lê Cẩm Tú",
                            Phone = "0912345678"
                        },
                        new
                        {
                            Id = 4,
                            CardNumber = "LIB-GIANG01",
                            Email = "hagiang.pham@gmail.com",
                            Name = "Phạm Hà Giang",
                            Phone = "0923456789"
                        },
                        new
                        {
                            Id = 5,
                            CardNumber = "LIB-HANLE01",
                            Email = "ngochan.le@gmail.com",
                            Name = "Lê Ngọc Hân",
                            Phone = "0934567890"
                        });
                });

            modelBuilder.Entity("MiniLibraryWeb.Models.Entities.BorrowTicket", b =>
                {
                    b.HasOne("MiniLibraryWeb.Models.Entities.Book", "Book")
                        .WithMany("BorrowTickets")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniLibraryWeb.Models.Entities.Reader", "Reader")
                        .WithMany("BorrowTickets")
                        .HasForeignKey("ReaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Reader");
                });

            modelBuilder.Entity("MiniLibraryWeb.Models.Entities.Book", b =>
                {
                    b.Navigation("BorrowTickets");
                });

            modelBuilder.Entity("MiniLibraryWeb.Models.Entities.Reader", b =>
                {
                    b.Navigation("BorrowTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
